// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdvWS7-4GsZJlvxYYuX3jeRRGXuG_qLA',
    appId: '1:765588215112:web:4d478b78115297b6768f7d',
    messagingSenderId: '765588215112',
    projectId: 'tutorialkelas-224a2',
    authDomain: 'tutorialkelas-224a2.firebaseapp.com',
    storageBucket: 'tutorialkelas-224a2.firebasestorage.app',
    measurementId: 'G-6ZXHZN1170',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXuVfoL6Hdlw7FubsCNvmue1toZZjtiA',
    appId: '1:765588215112:android:7f3bacee39db2944768f7d',
    messagingSenderId: '765588215112',
    projectId: 'tutorialkelas-224a2',
    storageBucket: 'tutorialkelas-224a2.firebasestorage.app',
  );
}
